wandb_version: 1

num_epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0
project_tag:
  desc: null
  value: unmeasured_confounding_binary
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713916296.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 15
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: darwin-x86_64
